import{a as w,S,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();const v="https://pixabay.com/api/",q="53360876-f97dd2c70b0e27b498deb3edc";async function u(o,t){const r={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15},{data:i}=await w.get(v,{params:r});return i}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),E=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(r=>`
            <a class="gallery-item" href="${r.largeImageURL}">
                <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
                <div class="info">
                    <p><b>Likes:</b> ${r.likes}</p>
                    <p><b>Views:</b> ${r.views}</p>
                    <p><b>Comments:</b> ${r.comments}</p>
                    <p><b>Downloads:</b> ${r.downloads}</p>
                </div>
            </a>`).join("");f.insertAdjacentHTML("beforeend",t),E.refresh()}function B(){f.innerHTML=""}function p(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function M(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}const P=document.querySelector(".form"),$=document.querySelector("input[name='search-text']"),O=document.querySelector(".load-more");let c="",s=1;const b=15;P.addEventListener("submit",x);O.addEventListener("click",A);async function x(o){if(o.preventDefault(),c=$.value.trim(),s=1,!c){a.warning({title:"Warning",message:"Please enter a search query!",timeout:2e3});return}B(),d(),p();try{const t=await u(c,s);if(!t.hits.length){a.error({title:"No results",message:"Sorry, no images match your search query."});return}y(t.hits),t.totalHits<=b&&(d(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results."})),M()}catch{L()}finally{g()}}async function A(){s++,p();try{const o=await u(c,s);y(o.hits),C(),s*b>=o.totalHits&&(d(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch{L()}finally{g()}}function C(){var r;const o=(r=document.querySelector(".gallery"))==null?void 0:r.firstElementChild;if(!o)return;const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}function L(){a.error({title:"Error",message:"Something went wrong. Try again later."})}
//# sourceMappingURL=index.js.map
